using System.ComponentModel.DataAnnotations;

namespace Gradely.Domain.Entities
{
    /// <summary>
    /// Represents an assignment that students can submit work for.
    /// 
    /// IN THE GRADELY FLOW:
    ///   1. A teacher (or admin/seed data) creates an Assignment
    ///   2. Students see the assignment list (GET /api/assignments)
    ///   3. Students upload a PDF submission for the assignment
    ///   4. The ML system grades the submission
    /// 
    /// WHY Guid FOR THE ID?
    ///   Unlike ApplicationUser which uses string IDs (from ASP.NET Identity),
    ///   our custom entities use Guid (Globally Unique Identifier).
    ///   Benefits:
    ///     - Can be generated client-side or server-side
    ///     - No collisions across databases
    ///     - Better for distributed systems
    ///   EF Core recognizes a property named "Id" as the primary key automatically.
    /// 
    /// RELATIONSHIPS:
    ///   One Assignment → Many Submissions (one-to-many)
    ///   The Submissions navigation property lets EF Core understand this relationship
    ///   and allows us to do things like: assignment.Submissions.Count()
    /// </summary>
    public class Assignment
    {
        /// <summary>
        /// Primary key — Guid auto-generated by the database.
        /// EF Core convention: a property named "Id" is automatically the PK.
        /// </summary>
        [Key]
        public Guid Id { get; set; }

        /// <summary>
        /// The assignment title shown to students (e.g. "Essay on Climate Change").
        /// [Required] ensures this can't be null or empty in the database.
        /// [MaxLength] creates a VARCHAR(200) column instead of unlimited NVARCHAR(MAX).
        /// </summary>
        [Required]
        [MaxLength(200)]
        public string Title { get; set; } = string.Empty;

        /// <summary>
        /// Detailed instructions for the assignment (optional).
        /// If null, the student just sees the title.
        /// </summary>
        public string? Description { get; set; }

        /// <summary>
        /// When the assignment is due. Students should submit before this date.
        /// We use UTC to avoid timezone confusion.
        /// </summary>
        public DateTime DueDate { get; set; }

        /// <summary>
        /// The maximum grade for this assignment (e.g. 100 points).
        /// The ML system will assign a grade between 0 and this value.
        /// </summary>
        public int MaxGrade { get; set; } = 100;

        /// <summary>
        /// When the assignment was created. Auto-set to UTC now.
        /// </summary>
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        // ── Navigation Property ──────────────────────────────────────
        /// <summary>
        /// All submissions for this assignment (one-to-many relationship).
        /// 
        /// WHY ICollection and not List?
        ///   ICollection is more abstract — EF Core can use any collection type internally.
        ///   We initialize it to an empty list to avoid null reference exceptions
        ///   when accessing assignment.Submissions before loading from DB.
        /// </summary>
        public ICollection<Submission> Submissions { get; set; } = new List<Submission>();
    }
}
