using System.ComponentModel.DataAnnotations;

namespace Gradely.Application.DTOs.Submissions
{
    /// <summary>
    /// Request DTO for submitting an assignment (uploading a PDF).
    /// 
    /// HOW THE SUBMISSION UPLOAD WORKS:
    ///   The student sends a multipart/form-data request with:
    ///   1. This DTO's fields (AssignmentId) → sent as form fields
    ///   2. The PDF file → sent as IFormFile (handled separately in the controller)
    /// 
    ///   We DON'T include IFormFile here because:
    ///   - DTOs live in the Application layer
    ///   - IFormFile is an ASP.NET Core type (API layer concern)
    ///   - The controller receives the file and passes it to the service separately
    /// 
    /// WHY ONLY AssignmentId?
    ///   - StudentId comes from the JWT token (extracted in the controller)
    ///     → students can't fake being someone else
    ///   - The file comes as IFormFile (not part of the DTO)
    ///   - FilePath and OriginalFileName are generated by the service
    ///   - Status is set automatically to "Submitted"
    ///   
    ///   So the student only needs to tell us WHICH assignment they're submitting to.
    /// 
    /// EXAMPLE form-data the client sends:
    ///   assignmentId: "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
    ///   file: [binary PDF data]
    /// </summary>
    public class SubmitAssignmentDto
    {
        /// <summary>
        /// The ID of the assignment the student is submitting to.
        /// Must be a valid existing assignment GUID.
        /// </summary>
        [Required(ErrorMessage = "Assignment ID is required.")]
        public Guid AssignmentId { get; set; }
    }
}
